name: Next.js Build and Docker Push Workflow

on:
  push:
    branches:
      - develop

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18" # You can specify your Node.js version here

      - name: Install dependencies
        run: npm install

      # - name: Create .env file
      #   run: |
      #     echo MONGODB_URI=${{ secrets.DEV_MONGODB_URI }} >> .env

      - name: Build Next.js Project
        run: npm run build

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t sargadi/joonweb:develop .
          docker push sargadi/joonweb:develop
